export const DIVISIONS = [
  "EDAPPAL",
  "KOTTAKKAL",
  "PARAPPANANGADI",
  "PONNANI",
  "PUTHANATHANI",
  "TANUR",
  "THENHIPPALAM",
  "TIRUR",
  "TIRURANGADI",
  "VAILATHUR",
  "VALANCHERY",
  "VENGARA",
];
export const COURSES = ["Commerce", "Science", "Humanities", "VHSE"];
export const SCHOOLS = [
  { name: "DHOHSS POOKARATHARA" },
  { name: "GHSS EDAPPAL" },
  { name: "GHSS KADANJERY" },
  { name: "GHSS KOKKUR" },
  { name: "GHSS THAVANOOR" },
  { name: "PCNGHSS MOOKUTHALA" },
  { name: "GHSS OTHUKKUNGAL" },
  { name: "GOVT RAJAS KOTTAKKAL" },
  { name: "HSS KOTTUR" },
  { name: "HSS PUTHUPPARAMB" },
  { name: "KHMHSS VALAKKULAM" },
  { name: "PKMMHSS EDARIKODE" },
  { name: "VHSS CHAPPANANGADI" },
  { name: "B E M H S S PARAPPANANGADI" },
  { name: "C B H S S PARAPPANANGADI" },
  { name: "M V H S S ARIYALLUR" },
  { name: "SNMHSS PARAPPANANGADI" },
  { name: "AV HSS THRIKKAVU" },
  { name: "GHSS MUKKALA" },
  { name: "GHSS PALAPETTY" },
  { name: "GHSS VANNERI" },
  { name: "GHSS VELIANCODE" },
  { name: "MES PONNANI" },
  { name: "MI HSS PONNANI" },
  { name: "BYKHSS VALAVANNUR" },
  { name: "CHSS CHERULAL" },
  { name: "GHSS MATTUMMAL" },
  { name: "GVHSS KALPAKANCHERY" },
  { name: "MSMHSS KALLINGALPARAMB" },
  { name: "NMHSS TIRUNNAVAYA" },
  { name: "VVMHSS VATTAPARAMB" },
  { name: "CPPHSS AYYAYA" },
  { name: "DGHSS DHEVATHAR" },
  { name: "GHSS KATILANGADI" },
  { name: "GHSS MANGADU" },
  { name: "GRFT VHSS" },
  { name: "SMMHSS RAYIRIMANGALAM" },
  { name: "CHSS VELIMUKK" },
  { name: "GHSS PERUVALLUR" },
  { name: "GMHSS UNIVERSITY" },
  { name: "GVHSS CHELARI" },
  { name: "MHSS MOONNIYUR" },
  { name: "NAJATH HSS PERUVALLUR" },
  { name: "NNMHSS CHELEMBRA" },
  { name: "CO OPERATIVE COLLEGE TIRUR" },
  { name: "GAID TIRUR" },
  { name: "GBHSS THRKANDIYUR" },
  { name: "GHSS CHERIYAMUNDAM" },
  { name: "GHSS EZHUR" },
  { name: "GHSS PURATHUR" },
  { name: "GVHSS PARAVANNA" },
  { name: "KHMHSS ALATHIYUR" },
  { name: "MALABAR HIGHER SECONDARY SCHOOL" },
  { name: "MMHSS KUTTAYI" },
  { name: "NAVODAYA COLLEGE ALATHIYUR" },
  { name: "UDAYA COLLEGE ALATHIYUR" },
  { name: "AR NAGAR HIGHER SECONDARY SCHOOL, CHENDAPURAYA" },
  { name: "CO-OPERATIVE HIGHER SECONDARY SCHOOL, TIRURANGADI" },
  { name: "GOVT. HIGHER SECONDARY SCHOOL,TIRURANGADI" },
  { name: "KMHSS KUTTOOR NORTH" },
  { name: "ORIENTAL HIGHER SECONDARY SCHOOL, TIRURANGADI" },
  { name: "SEETHI SAHIB MEMORIAL HIGHER SECONDARY SCHOOL, TIRURANGADI" },
  { name: "GVHSS PERUMANNA" },
  { name: "GVHSS PONMUDAM" },
  { name: "BHSS MAVANDIYOUR" },
  { name: "GHSS IRIMBILYAM" },
  { name: "GHSS KUTTIPURAM" },
  { name: "GHSS PERSHANUR" },
  { name: "MES VENDALOOR" },
  { name: "VHSS VALANCHERY" },
  { name: "AL - IHSAN HSS VENGARA" },
  { name: "CO - OPERATIVE COLLEGE VENGARA" },
  { name: "GMVHSS VENGARA" },
  { name: "GVHSS VENGARA" },
  { name: "IU ARTS PARAPPUR" },
  { name: "IUHSS PARAPPUR" },
  { name: "MALABAR COLLEGE HSS KUTTALUR" },
  { name: "MAMBAHUL HUDA HSS KUZHICHENA" },
  { name: "MUHSS OORAKAM" },
  { name: "PPTM COMMERCE HSS CHERUR" },
  { name: "PPTMYHSS CHERUR" },
];
